### ISSUE TITLE
ADownloader is crashing

### ISSUE THREAD

**Issue by Ashnaag** [denobisipsis/adownloader#130]
Hi,

After clicking any of the available resolution to download the video (https://www.zee5.com/tvshows/details/naaginn/0-6-131/episode-71-naaginn/0-1-manual_57agb0leqme0), adownloader is crashing.

Please can you check and help me in solving the issue.

Thanks and Regards,
Ashish Joshi

**Comment by Ashnaag** [comment]
Even when trying to download Voot Video (https://www.voot.com/shows/naagin/4/879088/the-naagin-returns/878645) Adownloader is crashing.

**Comment by denobisipsis** [comment]
I think is working now.

**Comment by Ashnaag** [comment]
yes its working now. Thanks
