### ISSUE TITLE
Hotstar 

### ISSUE THREAD

**Issue by ghost** [denobisipsis/adownloader#133]
Please add credentials option for hotstar.
And didn't understand that it works with VPN, can you explain?

**Comment by denobisipsis** [comment]
> Please add credentials option for hotstar.
> And didn't understand that it works with VPN, can you explain

Hard geoblocked, but it should work. Can you email me credentials? froheweihnachten2014@gmail.com

**Comment by ghost** [comment]
> > Please add credentials option for hotstar.
> > And didn't understand that it works with VPN, can you explain
> 
> Hard geoblocked, but it should work. Can you email me credentials? [froheweihnachten2014@gmail.com](mailto:froheweihnachten2014@gmail.com)

Sent you credentials......from mando@choco.la

**Comment by ghost** [comment]
https://www.hotstar.com/in/tv/big-city-greens/s-2479/space-chicken-steak-night/1260019799

Not working.
