### ISSUE TITLE
aha Video not working

### ISSUE THREAD

**Issue by padma-lakshmi** [denobisipsis/adownloader#134]
Hi, can you please add support for, also add login option for premium content : 

https://www.aha.video/movies/race-gurram

**Comment by denobisipsis** [comment]
Try now

**Comment by padma-lakshmi** [comment]
Working, thank you.

**Comment by ghost** [comment]
https://www.aha.video/originals/locked/parched/s1/e3

It's not working.

**Comment by denobisipsis** [comment]
added
