### ISSUE TITLE
Zee5 out of sync

### ISSUE THREAD

**Issue by ghost** [denobisipsis/adownloader#135]
For zee5(zeetv) content, the videos are out of sync with audio.. Actually video is accurate but not audio....

**Comment by denobisipsis** [comment]
Post link

**Comment by ghost** [comment]
> Post link

https://www.zee5.com/movies/details/naal/0-0-67717

**Comment by denobisipsis** [comment]
Just downloaded and no audio sync problems. Check that all audio chunks were downloaded.

**Comment by ghost** [comment]
> Just downloaded and no audio sync problems. Check that all audio chunks were downloaded.

Yeah we have to download 2 times... for any of zee5 content. First time it won't work, but will work second time..

**Comment by denobisipsis** [comment]
That means some audio chunks are not downloaded the first time. Check vpn and so. For prime hotstar videos, login is not the problem, they are drm'ed mpd (crypt protected)

**Comment by ghost** [comment]
> That means some audio chunks are not downloaded the first time. Check vpn and so. For prime hotstar videos, login is not the problem, they are drm'ed mpd (crypt protected)

What about single VIP movie[Endgame] that is not working? Any idea?

**Comment by denobisipsis** [comment]
DRmed

**Comment by ghost** [comment]
That's it.... Thanks
