### ISSUE TITLE
Hotstar Premium

### ISSUE THREAD

**Issue by ghost** [denobisipsis/adownloader#136]
Any Premium content like: https://www.hotstar.com/in/movies/becoming-warren-buffett/1770016243

Single VIP movie:
https://www.hotstar.com/in/movies/avengers-endgame/1260013556

are not working.....

Please tell, Is downloading premium content working?

Also anyway to add www.aha.video premium content.

**Comment by denobisipsis** [comment]
for aha video send login

**Comment by ghost** [comment]
> for aha video send login

I figured out that aha.video is same as hoichoi.tv, I've account in aha but not subscribed.
