### ISSUE TITLE
Add only audio option

### ISSUE THREAD

**Issue by ghost** [denobisipsis/adownloader#137]
Could you add an option to download only audio? because there are some videos of multiple audios.

**Comment by denobisipsis** [comment]
Send example

**Comment by ghost** [comment]
https://www.jiocinema.com/watch/movies/baywatch/0/0/edd3297036b911ea8019c7ab91ded325/0/0

https://www.jiocinema.com/watch/tv/phineas-and-ferb/1/1/1532343596451/2ed04440861b11e89e8fede614b72917/0

Also some other sites.

**Comment by ghost** [comment]
Also in hotstar for some videos, it says no viable stream found.

https://www.hotstar.com/in/tv/big-city-greens/s-2479/space-chicken-steak-night/1260019799

**Comment by denobisipsis** [comment]
No viable means DRM.

For jiocinema there is no language option in that stream.

**Comment by ghost** [comment]
> No viable means DRM.
> 
> For jiocinema there is no language option in that stream.

No,It's a multi-audio stream. Anyway sending someother examples.

https://www.jiocinema.com/watch/movies/cars/0/0/fa89064093f711e9bd37c55c59b32bc8/0/0

https://www.jiocinema.com/watch/movies/captain-america--the-first-avenger/0/0/f0f22800872d11e89e8fede614b72917/0/0

![Screenshot_20200216-192117](https://user-images.githubusercontent.com/59650273/74605830-92e45780-50f1-11ea-984f-1627ffe93c9e.jpg)

**Comment by denobisipsis** [comment]
i know it, but is not the same to view the stream, with multiple audios, and to download it. And for these videos, there is no alternative audio if you want to download it.

**Comment by ghost** [comment]
> i know it, but is not the same to view the stream, with multiple audios, and to download it. And for these videos, there is no alternative audio if you want to download it.

You mean no other audio available? That's why I sent screenshot showing 4 different languages... Please look into it...😁

**Comment by denobisipsis** [comment]
Yes, there are many audio tracks  but this occurs viewing the video through standard access which is DRM'ed. I use non standard access, which does not work for all videos, but permits you to download it.
