### ISSUE TITLE
Discovery Plus

### ISSUE THREAD

**Issue by ghost** [denobisipsis/adownloader#142]
Please check if it's possible to download the free content from discoveryplus.com .

**Comment by denobisipsis** [comment]
links like https://go.discovery.com/tv-shows/pandemic-covid-19/full-episodes/pandemic-covid-19 are working

**Comment by ghost** [comment]
I mean most of content is not available like https://www.discoveryplus.com/videos/truth-behind-the-moon-landing/the-hollywood-conspiracy . So please look into it. Also some videos contain multiple audios unlike go.discovery.com

**Comment by denobisipsis** [comment]
Try now

**Comment by ghost** [comment]
Thanks for adding support. But languages are no getting recognized

**Comment by ghost** [comment]
?lang= also not working for them.

**Comment by denobisipsis** [comment]
Please, add English,Tamil or Hindi

?lang=Hindi

**Comment by ghost** [comment]
I mean if we consider this https://www.discoveryplus.com/videos/you-have-been-warned/kings-of-carnage , it also consists of Bengali and Telugu which are on being detected, it only detects English, Hindi, Tamil. Sorry for interruption.

**Comment by denobisipsis** [comment]
Try now

**Comment by ghost** [comment]
Thank you
