### ISSUE TITLE
Hotstar Video not downloading

### ISSUE THREAD

**Issue by Ashnaag** [denobisipsis/adownloader#143]
Hi,

Instead of downloading the actual Video from hotstar, a small video clip is getting downloaded having message "This Version of Hotstar is no longer supported. Please download the latest version from the App store." Below is the screenshot for your reference.

![image](https://user-images.githubusercontent.com/54377665/78892439-f9994800-7a86-11ea-96eb-92248a7bb6d6.png)

Till yesterday I was able to download the actual Hotstar video. This error started from today morning. Please can you check and rectify the issue.

Thanks and Regards,
Ashish Joshi

**Comment by denobisipsis** [comment]
https://www.hotstar.com/tv/barathi-kannamma/s-2016/soundharya-slaps-kannamma/1100028262 is working. Post link

**Comment by Ashnaag** [comment]
Below is the link for your reference.

https://www.hotstar.com/in/tv/maharaj-ki-jai-ho/s-2570/sanjays-bold-decision/1000249332

**Comment by denobisipsis** [comment]
It's VIP, so no access

**Comment by padma-lakshmi** [comment]
> 
> 
> It's VIP, so no access

Even, free movies are also not downloading and also please enable auth module for hotstar VIP.

Free:
https://www.hotstar.com/in/movies/baahubali-the-beginning/1000074338/watch

**Comment by denobisipsis** [comment]
So fixed, i think

**Comment by padma-lakshmi** [comment]
Superb, It's working without any issues, plz close this thread.
