### ISSUE TITLE
Jiocinema bit-rate issue

### ISSUE THREAD

**Issue by padma-lakshmi** [denobisipsis/adownloader#145]
while try to download from the jiocinema it's not showing high bit-rates plz try to fix it.

https://www.jiocinema.com

**Comment by padma-lakshmi** [comment]
Any update on this ?

**Comment by denobisipsis** [comment]
Send link and login please

**Comment by padma-lakshmi** [comment]
> Send link and login please

https://www.jiocinema.com/watch/movies/bigil/0/0/9eb416b078a911ea9851635b182fc40d/0/0

sent mail to froheweihnachten2014@gmail.com

**Comment by padma-lakshmi** [comment]
Thank you so much, issue got resolved.
