### ISSUE TITLE
 Prime Video not getting downloaded

### ISSUE THREAD

**Issue by padma-lakshmi** [denobisipsis/adownloader#147]
Hi,
 I am also unable to download videos from amazon prime (https://www.primevideo.com/detail/0PQH591BNQNR565QSSK4II7RPT/) even after saving my amazon login credentials...
"You must enter credentials..." is being displayed even after credentials have been added.

Please help.

**Comment by scorpsannav** [comment]
Are you able to download from Hotstar? Kindly check n let me know..

**Comment by padma-lakshmi** [comment]
Yes, Hotstar working fine.

**Comment by padma-lakshmi** [comment]
Can anyone please help me with primevideo?

**Comment by denobisipsis** [comment]
Not updated. Maybe login mechanism is failing too. Wait

**Comment by scorpsannav** [comment]
> Yes, Hotstar working fine.

Now it is working..Thanks..

**Comment by padma-lakshmi** [comment]
waiting for primevideo login mechanism update.

**Comment by scorpsannav** [comment]
> waiting for primevideo login mechanism update.

I never tried which has credentials type video extracts.. Will it work? Have u extracted video from primevideo before?

**Comment by padma-lakshmi** [comment]
no, but credentials type videos like jio and aha working fine except primevideo.com

**Comment by scorpsannav** [comment]
> no, but credentials type videos like jio and aha working fine except primevideo.com

Ok...Let me also know if it works for u... Does MXplayer video downloads work for u?

**Comment by padma-lakshmi** [comment]
you can download directly with IDM or any video grab tool, content is not a DRM protected.

**Comment by scorpsannav** [comment]
> you can download directly with IDM or any video grab tool, content is not a DRM protected.

Ok Thanks in advance..Can give d any IDM tool name which is useful for this...

**Comment by padma-lakshmi** [comment]
> 
> 
> Not updated. Maybe login mechanism is failing too. Wait

Any update please ...
