### ISSUE TITLE
Downloaded Chunks not getting merged

### ISSUE THREAD

**Issue by Ashnaag** [denobisipsis/adownloader#148]
Hi,

I have downloaded few videos from hotstar post resolution of issue #146, the chunks are getting downloaded in their respective folder but chunks are not getting merged into a complete file.

Below are the logs that i can see on the screen of Adownloader.

1.00B hotstarTroubleFollowsShakunitypem3u8_190001920x1080.mkv downloaded
**No such file**
Module caudiovideo up to date
0.00B hotstarTroubleFollowsShakunitypem3u8_190001920x1080.mkv downloaded 
mkv on
Merging subtitles->...Wait the notification
Incrusting subtitles
Module isubs up to date
Chunks were preserved. If you want to delete them change m3delete in options.ini putting m3delete=1;
Muxing m3u8 files...

Please can you help.

Thanks

**Comment by denobisipsis** [comment]
Try deactivating subtitles

**Comment by Ashnaag** [comment]
Deactivating Subtitles did not work.

1.00B hotstarTroubleFollowsShakunitypem3u8_190001920x1080.mp4 downloaded
**No such file**
Module caudiovideo up to date
Dont want to mux caps
Module isubs up to date
Chunks were preserved. If you want to delete them change m3delete in options.ini putting m3delete=1;
Muxing m3u8 files...

**Comment by Ashnaag** [comment]
Hi...Any updates on this issue. I tried everything that has been suggested in issue #146 but still chunks are not getting merged into a single file. 

Issue is occurring for zee5 and hotstar videos

**Comment by Ashnaag** [comment]
As per comments on issue #146 the issue is solved and I have successfully downloaded videos from Zee5 and HotStar.
