### ISSUE TITLE
JioCinema

### ISSUE THREAD

**Issue by ghost** [denobisipsis/adownloader#151]
https://www.jiocinema.com/watch/movies/happy-sardar/0/0/faef6240805111ea8130191f9d063c85/0/0

Not working.

**Comment by padma-lakshmi** [comment]
Hi, I personally verified the above link, it's working perfectly. close this ticket.

**Comment by ghost** [comment]
> Hi, I personally verified the above link, it's working perfectly. close this ticket.

![Screenshot](https://user-images.githubusercontent.com/59650273/83511305-12a10100-a4ec-11ea-8f76-36a08fac32fd.png)

**Comment by denobisipsis** [comment]
You need credentials.
