### ISSUE TITLE
MX Player Videos not downloading

### ISSUE THREAD

**Issue by scorpsannav** [denobisipsis/adownloader#153]
Dear Team,

I am not able download videos from MX Player website
Below is the sample link.. Requesting you to resolve it.

https://www.mxplayer.in/movie/watch-chowka-movie-online-aec4d7230618d0f9b73036d840a390eb?watch=true

**Comment by denobisipsis** [comment]
DRM

**Comment by scorpsannav** [comment]
Does it mean it is not possible to download?
