### ISSUE TITLE
How to download SUN NXT videos

### ISSUE THREAD

**Issue by scorpsannav** [denobisipsis/adownloader#155]
Please let me know how to download Sun Nxt Videos

https://www.sunnxt.com/movie/detail/72228

**Comment by denobisipsis** [comment]
Fixed, from mxplay isnt possible to grab sunnxt id, but directly works. You need sunnxt login.

**Comment by scorpsannav** [comment]
Thanks.. I have SUNNXT login..How to download if soo..

**Comment by scorpsannav** [comment]
https://www.mxplayer.in/movie/watch-chowka-movie-online-aec4d7230618d0f9b73036d840a390eb?watch=true

Wrong Video downloaded in above link...Plz check..

**Comment by denobisipsis** [comment]
No, you have to download https://www.sunnxt.com/movie/detail/72228.

**Comment by scorpsannav** [comment]
https://www.sunnxt.com/movie/detail/72228

Above link not working for me..Not able to Download

![image](https://user-images.githubusercontent.com/65526797/85948790-53b3f600-b970-11ea-8cae-94262660a119.png)

**Comment by denobisipsis** [comment]
Try now

**Comment by scorpsannav** [comment]
I tried.. Still same pblm..

**Comment by denobisipsis** [comment]
And now?

**Comment by scorpsannav** [comment]
I can see only ....... dots
![image](https://user-images.githubusercontent.com/65526797/85950905-40f3ee00-b97d-11ea-8b1d-543afb2835a5.png)

**Comment by denobisipsis** [comment]
Please, reboot program and make the search, then copy all the window log and paste here

**Comment by scorpsannav** [comment]
Found...1 links 

{"status":"SUCCESS",
72228
XSRF-TOKEN=eyJpdiI6Ik90S3Z4YURPaVhNNmx4UHpnWmVBMnc9PSIsInZhbHVlIjoiNHNBWnZXcFZpWnYxM0FpMSsyMUx2dTcwVFZOVStMVVloZk5zMVdcL0VnT0JJcm1BNTA1YkVteGhHUHhwRWJNVjRXZ1QzeGlHamdWc0REenRcLzRVdDloZz09IiwibWFjIjoiY2Y3ODcwMzcwZGI0NDEzMTI2MDUxNzRmZTIxMjU1YmY1OTE2MzMwNjliZWQyZjBhZjY5NTA2NTI3YTQwMWQ0YyJ9;laravel_session=VbtwE9VRzomxzfGPEEzat0ZGukGdErBwxZHjBkyU;
Selected proxy from IN but unused cause you're there
You are in IN
Module nproxy up to date
Module sunnxt updated
Finished
Updating ffmpeg...
 good
Module redirector up to date
https://www.sunnxt.com/movie/detail/72228
Searching streams...
Booting in 31 seconds
Running...
FFmpeg allowed_extensions activated. This is a newer FFmpeg so some operations may fail. Please post them
Ready...
 good
Thank you for contributing santhosh.nav
Checking donation...
Donation...
Mux options false for internal use of ffmpeg. Dont change it if you dont know what are you doing
Structure...
	21-inichecks...set to Y
	14-getsubs...Y
	13-sout...#transcode{vcodec=mp4v,acodec=mpga,deinterlace,hq}:standard{access=file,mux=ts
	12-ydashwebm...false
	11-ydashmp4...false
	10-ychunk=...9000000
	9-muxoptions...false
	8-Audio output set to SAME
	7-Video output set to SAME
	6-Forcing proxy...N
	5-proxyuse...Use online proxies
	4-hdsparallel...set to 4
	3-m3delete...N
	2-m3parallel...set to 4
	1-fftemp not set
	0-Downloads folder set to C:\Adownloader\downloads
Options...
Adobe HDS funciona correctamente
AdobeHDS...
path...
SubtitleEdit...
modules...
rabcasm...
vlc...
ismdownloader...
ismdownloaderAVC1...
rtmpdump...
ffmpeg...
php...
SabreAMF...
external scripts...
curl...
7za...
aria2c...
curl...
Cacert...
Folders...
OK
Connection...
Inichecks...
Starting...
Adownloader Log...

**Comment by denobisipsis** [comment]
Send me your credentials (Do you have access to this video?)

**Comment by scorpsannav** [comment]
I emailed to Frohe Weihnachten ID

**Comment by denobisipsis** [comment]
ok, maybe you are outside India using a vpn. Then the problem is the vpn.

**Comment by scorpsannav** [comment]
I am in india only

**Comment by denobisipsis** [comment]
Now it should work (i hope, for me is working since the beginning...)

**Comment by scorpsannav** [comment]
Hahaha,,,Thanks For trying..But not working for me..Below are the images
![image](https://user-images.githubusercontent.com/65526797/85953323-304b7400-b98d-11ea-9c7c-786c9607ef64.png)


![image](https://user-images.githubusercontent.com/65526797/85953330-393c4580-b98d-11ea-8ab0-edd7624da102.png)

**Comment by denobisipsis** [comment]
Update program

http://atresdownloader.com/versions/a3toMP4v19.exe

Then update curl and aria 

(in options press buttons 18,19)

**Comment by denobisipsis** [comment]
Also fill in your sunnxt credentials in credentials

**Comment by scorpsannav** [comment]
Thanks..Its working now..

But only low resolution available. Can u plz let me know the solution for downloading high resolution

![image](https://user-images.githubusercontent.com/65526797/86020158-2c7b2880-ba45-11ea-9c0d-fbf2d4d205c4.png)

**Comment by denobisipsis** [comment]
Only low resolution

**Comment by scorpsannav** [comment]
Its not suitable for watching...Plz let me know any other option in this SW for downloading high resolution..

**Comment by denobisipsis** [comment]
Only non-DRM stream is low

**Comment by scorpsannav** [comment]
Ok.. Thanks for the support..

**Comment by scorpsannav** [comment]
https://www.sunnxt.com/movie/detail/17455

This is not working.. Can u please help me

**Comment by denobisipsis** [comment]
It works

**Comment by scorpsannav** [comment]
![image](https://user-images.githubusercontent.com/65526797/87217070-2f3e1d80-c363-11ea-98cf-223ade5478d9.png)


![image](https://user-images.githubusercontent.com/65526797/87217074-3fee9380-c363-11ea-9078-c56f5a1c7c71.png)


These are the images..Can u help me..Its not working for me

**Comment by denobisipsis** [comment]
You should to log in. Enter your credentials

**Comment by scorpsannav** [comment]
i have entered my sunxt logins

**Comment by scorpsannav** [comment]
Only this link works which u had fixed earlier..
https://www.sunnxt.com/movie/detail/72228

no other links in that website works

**Comment by scorpsannav** [comment]
oh no..Even that s not working..

https://www.sunnxt.com/movie/detail/72228

**Comment by denobisipsis** [comment]
You even need vpn. All work fine

**Comment by scorpsannav** [comment]
ok
