### ISSUE TITLE
Zee5

### ISSUE THREAD

**Issue by fisby0302** [denobisipsis/adownloader#156]
Hi. Zee5  is not working. I tried to update ffmpeg (ffmpeg version git-2020-06-28-4cfcfb3) but it automatically changes to ffmpeg version git-2020-05-04-5767a2e. 
https://www.zee5.com/tvshows/details/yeh-vaada-raha/0-6-2553/yeh-vaada-raha-episode-76/0-1-manual_1ubmg0vvsc00
![image](https://user-images.githubusercontent.com/59845766/86710573-cafa2180-c023-11ea-8a89-c2026179bc96.png)

**Comment by denobisipsis** [comment]
Fixed

**Comment by fisby0302** [comment]
Thank. Everything works with ffmpeg version git-2020-06-28-4cfcfb3. But when loading the link, the ffmpeg version changes to ffmpeg version git-2020-05-04-5767a2e. What should I do to prevent this from happening?

**Comment by denobisipsis** [comment]
Ok. I fixed the ffmpeg version while newer did not work, but this last seems to be fine. Then i have freed the update

**Comment by fisby0302** [comment]
thank. now everything is stable
