### ISSUE TITLE
IP limit

### ISSUE THREAD

**Issue by ghost** [denobisipsis/adownloader#157]
Hi,
"You've surpassed IP limit"  mean, how many devices can we run simultaneously?

**Comment by denobisipsis** [comment]
That's info from the site, not the program

**Comment by ghost** [comment]
That happens when I enter key.

**Comment by denobisipsis** [comment]
Update the program.

**Comment by ghost** [comment]
Options checked
Please support this program
You have surpassed the ip limit
Checking donation...
You're up to date
Actual minor version d11f621fb32b847f45a02a96cdc429a5
Checking minor...wait...
You have the latest major version v19
Checking latest...
You're up to date
Actual minor version d11f621fb32b847f45a02a96cdc429a5
Checking minor...wait...
You have the latest major version v19
Checking latest...
Booting in 207 seconds
Running...
FFmpeg allowed_extensions activated. This is a newer FFmpeg so some operations may fail. Please post them
Ready...
Options checked
Please support this program
Checking donation...
Donation...
Mux options false for internal use of ffmpeg. Dont change it if you dont know what are you doing
Structure...
	22-inichecks...set to Y
	15-getsubs...Y
	14-sout...#transcode{vcodec=mp4v,acodec=mpga,deinterlace,hq}:standard{access=file,mux=ts
	13-ydashwebm...false
	12-ydashmp4...false
	11-ychunk=...9000000
	10-muxoptions...true
	9-Audio output set to SAME
	8-Video output set to SAME
	7-Forcing proxy...N
	6-proxyuse...Don't use proxies
	5-hdsparallel...set to 4
	4-hlsrelaunch...N
	3-m3delete...N
	2-m3parallel...set to 10
	1-fftemp not set
	0-Downloads folder set to C:\Adownloader\downloads
Options...
Adobe HDS funciona correctamente
AdobeHDS...
path...
SubtitleEdit...
modules...
rabcasm...
vlc...
ismdownloader...
ismdownloaderAVC1...
rtmpdump...
ffmpeg...
php...
SabreAMF...
external scripts...
curl...
7za...
aria2c...
curl...
Cacert...
Folders...
OK
Connection...
Inichecks...
Starting...
Adownloader Log...

**Comment by denobisipsis** [comment]
Wow, 1000 ip's with that key and one donation.

**Comment by ghost** [comment]
LOL, omg 1000!

**Comment by ghost** [comment]
BTW the number refresh in time? or just are those IPs used in whole time?

**Comment by denobisipsis** [comment]
Whole time.

**Comment by ghost** [comment]
As IP's change periodically, we can use program for only 1000times?

**Comment by denobisipsis** [comment]
Maybe they are ip's from different users.

**Comment by ghost** [comment]
As it's a 2 year old key, might have logged several times. Instead of 1000 IP limit, it's better key is only accessed by only 1 or 2 IPs at a time.

**Comment by denobisipsis** [comment]
Better donate and use your key ;)
