### ISSUE TITLE
JIO CINEMA DOWNLOAD ERROR !!!

### ISSUE THREAD

**Issue by PlayerUnknown53** [denobisipsis/adownloader#158]
***{"code":400,"message":"Caught Exception","e":{}}**   
Parallel downloading 100 chunks. To change it modify the field M3parallel
Using aria2c parallel
There are 239 chunks to download...
Getting manifest...
http://jiobeats.cdn.jio.com/vod/_definst_/smil:vod/13/97/320395a00ff511e8ba4283afdd11d221.smil/chunklist_b9192000_cfdm9kLzEzLzk3LzMyMDM5NWEwMGZmNTExZThiYTQyODNhZmRkMTFkMjIxLnR0bWw=.m3u8
www.jiocinema.com
Name is jioTheMusicVideotypem3u8_91900NoRESOLUTION.mp4
Fixed mux-options:  false 
Module ffmpeg up to date
Downloading jioTheMusicVideotypem3u8_91900NoRESOLUTION.mp4
Processing m3u8 bitrate m3u8_91900NoRESOLUTION
Found...12 links 
Subtitle's download error https://jiocinemaweb.cdn.jio.com/jioimages.cdn.jio.com/content/entry/data/13/97/320395a00ff511e8ba4283afdd11d221.srt
Selected proxy from IN but unused cause you're there
You are in IN
Module nproxy up to date
https://jiocinemaweb.cdn.jio.com/jioimages.cdn.jio.com/content/entry/data/13/97/320395a00ff511e8ba4283afdd11d221.srt
Getting manifest m3u8...
Module m3 up to date
Selected proxy from IN but unused cause you're there
You are in IN
Module nproxy up to date
1520603823157 320395a00ff511e8ba4283afdd11d221
eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1bmlxdWUiOiJiYTU3Nzg1Mi1jMzFmLTQ5OWYtOTA2Ny05MGRmYzVlNjlmYzkiLCJ1c2VyVHlwZSI6IlJJTHBlcnNvbiIsImF1dGhMZXZlbCI6IjQwIiwiZGV2aWNlSWQiOiI2MGI1MzM3NWQxZDU0MjVhNTgzYzhmMjVjMzU1YjI3MDA4ZTkwMjkwMDcxOTIzNGQxODdiYzA2MDZmYWQ0MjNhNDFiOWNkMWExYWE3ZGUxNWYyZDcyNTkxMjEzZjJlOGZhOGJjM2JiNGEwZDE1MjM2YjVjNTZlYzQ4MjI2ZGJhZCIsImp0aSI6IjYzYTRhMzUyLTgzMGUtNDZiZS1iOTAwLWU4YTc0MDliYjA0YSIsImlhdCI6MTU5NTM2MzQ5NX0.7tJy1432qLzBPDXDeiPUoohIU6q-31WROh5RFu5sB6E
Module jio up to date
 good
Module redirector up to date
https://www.jiocinema.com/watch/tv/boygiri/1/1/1520603823157/320395a00ff511e8ba4283afdd11d221/0
Searching streams...

**Comment by denobisipsis** [comment]
Just fixed,
