### ISSUE TITLE
ALT BALAJI !!

### ISSUE THREAD

**Issue by PlayerUnknown53** [denobisipsis/adownloader#159]
I have tried many time not working www.altbalaji,com only the 1st episode downloading after then no luck :(.

Also 

https://www.sonyliv.com/shows/undekhi-showid/the-things-that-men-do-1000047341?watch=true

This not working..

**Comment by denobisipsis** [comment]
For sonyliv, that stream is DRMed. And for altbalaji, many streams are DRMed, but to check please post link

**Comment by PlayerUnknown53** [comment]
Its possible to download below link..

https://cdn.cloud.altbalaji.com/content/2018-09/5013-5ba34059bd2eb/manifest.m3u8

https://www.altbalaji.com/506f53f4-e802-4b07-80cf-42193074c020

Its widewine DRM .. i think so..

**Comment by denobisipsis** [comment]
Yes, fairplay
