### ISSUE TITLE
JIO CINEMA SUBSTITLE DOWNLOAD ERROR !!

### ISSUE THREAD

**Issue by PlayerUnknown53** [denobisipsis/adownloader#160]
Subtitle's download error https://jiocinemaweb.cdn.jio.com/jioimages.cdn.jio.com/content/entry/data/13/97/320395a00ff511e8ba4283afdd11d221.srt
Selected proxy from IN but unused cause you're there
You are in IN
Module nproxy up to date

**Comment by denobisipsis** [comment]
link?

**Comment by PlayerUnknown53** [comment]
https://www.jiocinema.com/watch/tv/boygiri/1/1/1520603823157/320395a00ff511e8ba4283afdd11d221/0

**Comment by denobisipsis** [comment]
No problem here,

**Comment by PlayerUnknown53** [comment]
Yeah .. its old version.. well uupdated now all good.. :) hope soon amazon will work ..
