### ISSUE TITLE
zee5 Substitle Conversion error...

### ISSUE THREAD

**Issue by PlayerUnknown53** [denobisipsis/adownloader#163]
https://www.zee5.com/zee5originals/details/babbar-ka-tabbar/0-6-tvshow_753221809/episode-23-jamia-falls-in-love-with-doctor/0-1-168322

Found...7 links 
Subtitle's conversion error https://zee5vod.akamaized.net/drm1/PRIORITY1080/ORIGINALS/REPACAKGE/BABBAR_KA_TABBAR_Season_2/BABBAR_KA_TABBAR_SEASON2_HINDI_EP23_hi.mp4/manifest-en.vttmanifest-en.vtt
Getting and formatting captions...
Subtitle's conversion error https://zee5vod.akamaized.net/drm1/PRIORITY1080/ORIGINALS/REPACAKGE/BABBAR_KA_TABBAR_Season_2/BABBAR_KA_TABBAR_SEASON2_HINDI_EP23_hi.mp4/manifest-en.vtt
Getting and formatting captions...
Subs found in en
https://zee5vodnd.akamaized.net/hls1/PRIORITY1080/ORIGINALS/REPACAKGE/BABBAR_KA_TABBAR_Season_2/BABBAR_KA_TABBAR_SEASON2_HINDI_EP23_hi.mp4/audio/aac/en/hdntl=exp=1596731503~acl=%2f*~data=hdntl~hmac=127bf30dca6bc1e9d11f0e8472930d3c194e29011a39fcfb4c530d0975465cb6/stream.m3u8?aka_me_session_id=AAAAAAAAAABvMCxfAAAAAEc7ZzXZKuaUoRAEv4BbUqLmku+vzEfsT+fT42upKp%2fPnp0lbbbUD5k4eXMRfFT8QkVxdL30XpnG language hi 
Getting manifest m3u8...
hi
Module m3 up to date
https://zee5vodnd.akamaized.net/hls1/PRIORITY1080/ORIGINALS/REPACAKGE/BABBAR_KA_TABBAR_Season_2/BABBAR_KA_TABBAR_SEASON2_HINDI_EP23_hi.mp4/index.m3u8?hdnea=st=1596643571~exp=1596646571~acl=/*~hmac=a970ef7c7328e927e343446fa132211635f518f24a52aeda8f8f1bd0e672f197
Select language adding to URL ?lang=lang, i.e. ?lang=hi
There are these language possibilities: hi,
Not downloadable. DRM.
1 cycle
season 0-2-babbarkatabbar-season_1915767142
season 0-2-babbarkatabbar-season_945853791
0-1-168322
Found 1

Please check unable to download susbtitle.

**Comment by denobisipsis** [comment]
Subtitles doesnt work even on browser. 

Batch download: you have 2 posibilities,

1- pasting links in the program, you dont have to wait the downloading of previous streams to add more
2- opening several instances of the program

**Comment by PlayerUnknown53** [comment]
I have fix that...
