### ISSUE TITLE
SonyLiv audio ts/aac files are not downloaded

### ISSUE THREAD

**Issue by mistryjay-tech** [denobisipsis/adownloader#171]
After video download is complete audio is missing.
Checking the ts files download folder the aac files are not downloaded even though there is the a file named
x0typem3u8_13300960x540.mp4.m3u8ufcaudio.m3u8
in the download folder
which has lines similar to this
#EXTM3U
#EXT-X-VERSION:4
#EXT-X-TARGETDURATION:5
#EXT-X-MEDIA-SEQUENCE:1
#EXT-X-PLAYLIST-TYPE:VOD
#EXTINF:4,
show_ssssssss_ep14_LLL64k20201203T103947_00001.aac
#EXTINF:4,
show_ssssssss_ep14_LLL64k20201203T103950_00002.aac
#EXTINF:4,
show_ssssssss_ep14_LLL64k20201203T103952_00003.aac
....

The separate download of audio aac and video ts was working a few days ago. S
omething must have changed in the scripts.
I hope this will be fixed in future updates.
Thanks

**Comment by denobisipsis** [comment]
link

**Comment by mistryjay-tech** [comment]
Sorry. I forgot about it.

https://www.server/shows/showname-1700000311/showtitle-1000098647

(edited to remove the actual link)

**Comment by denobisipsis** [comment]
Fixed

**Comment by mistryjay-tech** [comment]
Thank you. All is good now.
