### ISSUE TITLE
Zee5 not working

### ISSUE THREAD

**Issue by Ashnaag** [denobisipsis/adownloader#182]
Please can you check as Zee5 is not showing download options.

![image](https://user-images.githubusercontent.com/54377665/121592973-fd44a800-ca58-11eb-912e-bfbf29a2e798.png)

**Comment by denobisipsis** [comment]
Please post link

**Comment by Ashnaag** [comment]
https://www.zee5.com/tvshows/details/adhuri-kahaani-humari/0-6-201/adhuri-kahaani-humari-episode-49-january-20-2016-full-episode/0-1-49048

and

https://www.zee5.com/tvshows/details/adhuri-kahaani-humari/0-6-201/adhuri-kahaani-humari-episode-55-january-28-2016-full-episode/0-1-49042

are two examples

**Comment by denobisipsis** [comment]
try now

**Comment by Ashnaag** [comment]
Videos downloaded....Thanks a ton for your help
