### ISSUE TITLE
Zee5 chunks not getting merged

### ISSUE THREAD

**Issue by Ashnaag** [denobisipsis/adownloader#186]
Hi,

Chunks for Videos from Zee5 are not getting merged into a single file.

https://www.zee5.com/tvshows/details/bhabi-ji-ghar-par-hai/0-6-199/bhabi-ji-ghar-par-hai-july-19-2021/0-1-manual-2ri9d8pi1krg

1.00B zeetvAnitaSeesChhaaviJholkarsSpirit_hitypem3u8_523001920x1080.mp4 downloaded
No such file
Module caudiovideo up to date
Chunks were preserved. If you want to delete them change m3delete in options.ini putting m3delete=1;
Muxing m3u8 files...

You have a new option called muxoptions

if you put false, the program uses ffmpeg with internal predefined options for muxing

if you put raw, the program doesnt use ffmpeg and makes a raw concatenating of chunks

if you put other, nothing, i.e. muxoptions=; , or valid ffmpeg options, program applies them

C:\Users\joshe\Downloads\New folder\Temp
Parallel downloading 4 chunks. To change it modify the field M3parallel
Using aria2c parallel
There are 214 chunks to download...
zee5
Selected proxy from IN but unused cause you're there
You are in IN
Module nproxy up to date
Getting manifest...
https://zee5vodnd.akamaized.net/hls1/elemental/hls/TV_SHOWS/AND_TV/July2021/19072021/Episode/BQC_CS_Bhabi_Ji_Ghar_Par_Hai_Ep1594_Episode_19072021_hi_9857aff50c906d3374554b4b2b267ab7/index1080lowp/hdntl=exp=1626885541~acl=%2f*~data=hdntl~hmac=f2b98b4c445a62f43389040ff84385de752c5bf381c7688a5c44815a782448da/1080lowp.m3u8?aka_me_session_id=AAAAAAAAAAClTfhgAAAAAJ7GPnSBfjk8in9vSNP+top6v0CRjROaznHXVtRTZ78wbRD0Ro8KAg+YRDTgCN20UiqUB+THcfYx&aka_media_format_type=hls
www.zee5.com
Name is zeetvAnitaSeesChhaaviJholkarsSpirit_hitypem3u8_523001920x1080.mp4
Fixed mux-options:  false 
C:\Users\joshe\Downloads\New folder\Temp
Module ffmpeg up to date
Downloading zeetvAnitaSeesChhaaviJholkarsSpirit_hitypem3u8_523001920x1080.mp4
Processing m3u8 bitrate m3u8_523001920x1080
Found...8 links 
Subs found in en
Getting manifest m3u8...
hi
Module m3 up to date
https://zee5vodnd.akamaized.net/hls1/elemental/hls/TV_SHOWS/AND_TV/July2021/19072021/Episode/BQC_CS_Bhabi_Ji_Ghar_Par_Hai_Ep1594_Episode_19072021_hi_9857aff50c906d3374554b4b2b267ab7/index.m3u8?hdnea=st=1626797625~exp=1626800625~acl=/*~hmac=0450678e5d9b2f25a47d88697524d0337d5981f6d7db5b97c45ada016c717761
Select language adding to URL ?lang=lang, i.e. ?lang=hi
There are these language possibilities: hi,
Not downloadable. DRM.
1 cycle
season 0-2-BhabijiGharParHain1
0-1-manual-2ri9d8pi1krg
Found 1
Module zeetv up to date
Finished
Extract's error dll curl
Updating curl dll...
 good
Module redirector up to date
https://www.zee5.com/tvshows/details/bhabi-ji-ghar-par-hai/0-6-199/bhabi-ji-ghar-par-hai-july-19-2021/0-1-manual-2ri9d8pi1krg

Please can you help with this issue.

I had faced similar kind of issue in past. #146 was the issue for which you had given a solution. Please can you fix this issue as well.

Thanks in Advance

**Comment by denobisipsis** [comment]
It works, update ffmpeg, dont use proxy

**Comment by Ashnaag** [comment]
Still no luck...I tried updating the ffmpeg

Finished
Updating ffmpeg...

Post update this is the the ffmpeg version - ffmpeg version N-74158-gf977e69

![image](https://user-images.githubusercontent.com/54377665/126868587-8e54c635-7a30-4f9a-8068-071e9079b343.png)


Chunks are still not getting merged

**_zeetvAnitaSeesChhaaviJholkarsSpirit_hitypem3u8_523001920x1080.mp4 downloaded
No such file_**
Module caudiovideo up to date
Chunks were preserved. If you want to delete them change m3delete in options.ini putting m3delete=1;
Muxing m3u8 files...

You have a new option called muxoptions

if you put false, the program uses ffmpeg with internal predefined options for muxing

if you put raw, the program doesnt use ffmpeg and makes a raw concatenating of chunks

if you put other, nothing, i.e. muxoptions=; , or valid ffmpeg options, program applies them

C:\Users\joshe\Downloads\New folder\Temp
Parallel downloading 4 chunks. To change it modify the field M3parallel
Using aria2c parallel
There are 214 chunks to download...
zee5
Selected proxy from IN but unused cause you're there
You are in IN
Module nproxy up to date
Getting manifest...
https://zee5vodnd.akamaized.net/hls1/elemental/hls/TV_SHOWS/AND_TV/July2021/19072021/Episode/BQC_CS_Bhabi_Ji_Ghar_Par_Hai_Ep1594_Episode_19072021_hi_9857aff50c906d3374554b4b2b267ab7/index1080lowp/hdntl=exp=1627215700~acl=%2f*~data=hdntl~hmac=8f6b3fa34b0f04044d563345b304c05c636460f36c4d0e9918505dcecd21f426/1080lowp.m3u8?aka_me_session_id=AAAAAAAAAABUV%2f1gAAAAAPQMe3faPqm6AgsQJb7G68s9ylwX%2f2yYLv3pazyTDzLo4WW9I09vVSyIfHoDqPMCANMLKCCBQSKk&aka_media_format_type=hls
www.zee5.com
Name is zeetvAnitaSeesChhaaviJholkarsSpirit_hitypem3u8_523001920x1080.mp4
Fixed mux-options:  false 
C:\Users\joshe\Downloads\New folder\Temp
Module ffmpeg up to date
Downloading zeetvAnitaSeesChhaaviJholkarsSpirit_hitypem3u8_523001920x1080.mp4
Processing m3u8 bitrate m3u8_523001920x1080
Found...8 links 
Subs found in en
Getting manifest m3u8...
hi
Module m3 up to date
https://zee5vodnd.akamaized.net/hls1/elemental/hls/TV_SHOWS/AND_TV/July2021/19072021/Episode/BQC_CS_Bhabi_Ji_Ghar_Par_Hai_Ep1594_Episode_19072021_hi_9857aff50c906d3374554b4b2b267ab7/index.m3u8?hdnea=st=1627127798~exp=1627130798~acl=/*~hmac=e74416f3a3a9a6f8bf25ae715e42fb59430c560d2e7ef6eafed33295bc09bf96
Select language adding to URL ?lang=lang, i.e. ?lang=hi
There are these language possibilities: hi,
Not downloadable. DRM.
1 cycle
season 0-2-BhabijiGharParHain1
0-1-manual-2ri9d8pi1krg
Found 1
Module zeetv up to date
Finished
Extract's error dll curl
Updating curl dll...
 good
Module redirector up to date
https://www.zee5.com/tvshows/details/bhabi-ji-ghar-par-hai/0-6-199/bhabi-ji-ghar-par-hai-july-19-2021/0-1-manual-2ri9d8pi1krg
Searching streams...
Finished

**Comment by denobisipsis** [comment]
Download https://github.com/BtbN/FFmpeg-Builds/releases/download/autobuild-2021-07-24-12-36/ffmpeg-N-103060-g88b6342c2b-win64-lgpl.zip and unzip ffmpeg.exe to tools folder.

**Comment by Ashnaag** [comment]
It worked...Thanks a ton for your help....This also fixed my earlier issue #179...you are the best
