### ISSUE TITLE
Wrong video getting downloaded from Voot

### ISSUE THREAD

**Issue by Ashnaag** [denobisipsis/adownloader#192]
Hello

When I enter below Naagin 6 Episode 54 VOOT URL to download it, the Video gets downloaded but instead of downloading episode 54, Episode 53 is getting downloaded.

https://www.voot.com/shows/naagin/6/1257363/mehek-releases-nashika/1356003

Please can you check

Thanks and regards,
Ashnaag

**Comment by denobisipsis** [comment]
Checkit now

**Comment by Ashnaag** [comment]
Hi.

The issue is still there. it shows that Episode 54 has been downloaded but when you play the downloaded video Episode 53 is played i.e. The video is of Episode 53 even though the application shows that Episode 54 is downloaded. Below is the URL of Episode 53 so that you can see that both online Episode 53 video and downloaded Episode 54 are same even though URL's for Episode 53 and Episode 54 are different.

Episode 53 -- https://www.voot.com/shows/naagin/6/1257363/mehek-s-cruel-intentions/1355728

Episode 54 -- https://www.voot.com/shows/naagin/6/1257363/mehek-releases-nashika/1356003

Thanks and Regards,
Ashnaag

**Comment by denobisipsis** [comment]
I dont know if online you can see the right episode, but i think it must be a temporary  error, the video downloaded responds to the info data received

**Comment by Ashnaag** [comment]
The issue is still there....I have downloaded the video again but instead of episode 54, episode 53 is getting downloaded

**Comment by denobisipsis** [comment]
Now you should login. It works, use VPN

**Comment by Ashnaag** [comment]
Issue is still there but I have managed to download video from different portal
