### ISSUE TITLE
zee5 0 chunks

### ISSUE THREAD

**Issue by mannnan** [denobisipsis/adownloader#193]
https://www.zee5.com/global/tv-shows/details/rettai-roja/0-6-1978/will-neeli-kill-manga/0-1-6z5201088

this links show the downloadable links but says 0 chunks downloaded
pls fix this

**Comment by denobisipsis** [comment]
Try now

**Comment by mannnan** [comment]
There are 0 chunks to download...

https://www.zee5.com/global/tv-shows/details/thalayanai-pookal/0-6-323/thalayanai-pookal/0-1-77810

pls fix it
