### ISSUE TITLE
NJPW World issue?

### ISSUE THREAD

**Issue by ItDoesntMatter** [denobisipsis/adownloader#87]
Hi again,

could you please check if NJPW World changed something?
If I want to start getting a file, whole program freezes and never comes back.

Thanks for your awesome work! :-)

**Comment by denobisipsis** [comment]
Check it now

**Comment by wukongtea** [comment]
@denobisipsis  ,can u get qq-video without logo?

**Comment by ItDoesntMatter** [comment]
@denobisipsis sorry, I was very busy during the week due to work.
I checked and I was able to get my file.

So, it looks like it's fixed - thank you very much!
