### ISSUE TITLE
Help you big brother, download iqiyi high quality 1080P or 4k video

### ISSUE THREAD

**Issue by lki2019** [denobisipsis/adownloader#95]
My sister has iqiyi membership account, she would like to download the highest quality to the computer point of view, online look too card,

http://www.iqiyi.com/v_19rr7p0jss.html

How can I ask for the highest quality?

Is there a finished product online that can directly parse the URL?

**Comment by denobisipsis** [comment]
you can use this http://www.mediafire.com/file/vpa94k3z45dpaed/a3toMP4v18.1FULL.exe. In login's list select iqiyi and fill in user and password not with credentials but with cookies P00001 and P00003. To know them, login via web and with debugger see these cookies. To check it send me your credentials

**Comment by lki2019** [comment]
Where the account and password, is to iqiyi membership account and password?

![qq 20170902175424](https://user-images.githubusercontent.com/30022431/29994704-7309b1f0-9008-11e7-8aac-54fe984f9012.png)

**Comment by denobisipsis** [comment]
login web with inspector activated. Then search the call to 

http://apollo.iqiyi.com/validate

In Response Headers take cookies

Set-Cookie:P00001=....; Domain=.iqiyi.com; Expires=Fri, 01-Dec-2017 11:04:54 GMT; Path=/

Set-Cookie:P00003=...; Domain=.iqiyi.com; Expires=Fri, 01-Dec-2017 11:04:54 GMT; Path=/


Fill use with P00003 and password with P00001

**Comment by lki2019** [comment]
I do not understand, such as this video

http://www.iqiyi.com/v_19rr8ketuo.html#vfrm=24-9-0-1

Login with member account, switch to 4K resolution

导出了cookies 

<pre><code>
# Netscape HTTP Cookie File
# http://curl.haxx.se/rfc/cookie_spec.html
# This is a generated file!  Do not edit.

.iqiyi.com	TRUE	/	FALSE	1504268293	CM0001	1
.iqiyi.com	TRUE	/	FALSE	1504323446	H_RENEW_COUNT	1504237046213
.iqiyi.com	TRUE	/	FALSE	1535803992	Hm_lvt_53b7374a63c37483e5dd97d78d9bb36e	1504257458,1504257645,1504257686,1504267970
.iqiyi.com	TRUE	/	FALSE	3651720694	P00001	a5rahekOUu0GPBPhkYassdWu6Nwzv7gxvACLbQlZm1RxghQ3DUOJRZYQut6y9vXNqNc70
.iqiyi.com	TRUE	/	FALSE	1512011808	P00002	%7B%22uid%22%3A%221450289006%22%2C%22user_name%22%3A%2218639808042%22%2C%22email%22%3A%22544451161%40qq.com%22%2C%22nickname%22%3A%22%5Cu8f69%5Cu8f95%5Cu6668%5Cu6656%22%2C%22pru%22%3A1450289006%2C%22type%22%3A11%2C%22pnickname%22%3A%22%5Cu8f69%5Cu8f95%5Cu6668%5Cu6656%22%7D
.iqiyi.com	TRUE	/	FALSE	1512011808	P00003	1450289006
.iqiyi.com	TRUE	/	FALSE	3651719445	P00004	465369725.1504235797.acc1b5d1bc
.iqiyi.com	TRUE	/	FALSE	1512011808	P00007	a5rahekOUu0GPBPhkYassdWu6Nwzv7gxvACLbQlZm1RxghQ3DUOJRZYQut6y9vXNqNc70
.iqiyi.com	TRUE	/	FALSE	1512011808	P00010	1450289006
.iqiyi.com	TRUE	/	FALSE	1512011808	P000email	544451161%40qq.com
.iqiyi.com	TRUE	/	FALSE	1512011808	P00PRU	1450289006
.iqiyi.com	TRUE	/	FALSE	1512011808	P01010	1504281600
.iqiyi.com	TRUE	/	FALSE	1504322212	QC001	1
.iqiyi.com	TRUE	/	FALSE	1535803969	QC005	4af0df675151e20f393e12624e86fcc9
.iqiyi.com	TRUE	/	FALSE	1535803998	QC006	uk6ky4wvlpfbmz1b56vmsvud
.iqiyi.com	TRUE	/	FALSE	1535803969	QC008	1504235782.1504247338.1504267969.9
.iqiyi.com	TRUE	/	FALSE	1535794754	QC021	%5B%7B%22key%22%3A%22%E9%82%A3%E6%99%82%E8%8A%B1%E5%A5%BD%E6%9C%88%E6%AD%A3%E5%9C%93%22%7D%2C%7B%22key%22%3A%22%E7%BB%A3%E6%98%A5%E5%88%802%22%7D%5D
.iqiyi.com	TRUE	/	FALSE	1535771809	QC116	544451161%40qq.com
.iqiyi.com	TRUE	/	FALSE	1535803999	QC118	%7B%22color%22%3A%22FFFFFF%22%2C%22channelConfig%22%3A1%2C%22hadTip%22%3A1%2C%22isOpen%22%3A1%2C%22speed%22%3A18%2C%22density%22%3A40%2C%22opacity%22%3A68%2C%22isFilterColorFont%22%3A1%2C%22proofShield%22%3A0%2C%22forcedFontSize%22%3A24%2C%22isFilterImage%22%3A1%7D
.iqiyi.com	TRUE	/	FALSE	1535794754	QC124	1%7C0
.iqiyi.com	TRUE	/	FALSE	1535771819	QC134	%7B%221450289006%22%3A%5B1504235818855%5D%7D
.iqiyi.com	TRUE	/	FALSE	1535803998	QC159	%7B%22color%22%3A%22FFFFFF%22%2C%22channelConfig%22%3A0%2C%22hadTip%22%3A1%2C%22isOpen%22%3A0%2C%22speed%22%3A10%2C%22density%22%3A30%2C%22opacity%22%3A68%2C%22isFilterColorFont%22%3A1%2C%22proofShield%22%3A0%2C%22forcedFontSize%22%3A24%2C%22isFilterImage%22%3A1%2C%22isset%22%3A1%7D
.iqiyi.com	TRUE	/	FALSE	1506827807	QC160	%7B%22u%22%3A%2218639808042%22%2C%22lang%22%3A%22%22%2C%22local%22%3A%7B%22name%22%3A%22%E4%B8%AD%E5%9B%BD%E5%A4%A7%E9%99%86%22%2C%22init%22%3A%22Z%22%2C%22rcode%22%3A48%2C%22acode%22%3A%2286%22%7D%2C%22type%22%3A%22p%22%7D
.iqiyi.com	TRUE	/	FALSE	1535771811	QC911	%2C5%2C
.iqiyi.com	TRUE	/	FALSE	1504269799	QILINPUSH	1
.iqiyi.com	TRUE	/	FALSE	1535771821	QIYUECK	qy_pc_22509b6bf99244af88607fbaf90af8ed
.iqiyi.com	TRUE	/	FALSE	1535803992	QP001	0
.iqiyi.com	TRUE	/	FALSE	1504354399	QY00001	1450289006
.iqiyi.com	TRUE	/	FALSE	1535371995	T00404	ae5cf54b016014c79a66abce057c2987
.iqiyi.com	TRUE	/	FALSE	1504686152	T00700	EgcIz7-tIRABEgcIkMDtIRABEgcIhcDtIRAB
.iqiyi.com	TRUE	/	FALSE	1504323587	TQC022	%7B%22au%22%3A%22a5rahekOUu0GPBPhkYassdWu6Nwzv7gxvACLbQlZm1RxghQ3DUOJRZYQut6y9vXNqNc70%22%2C%22ak%22%3A%22426ffm24jXUKm125MtfkqavsM0MU55AkyH7kNa0m39i7TxOugrcm4%22%7D
.iqiyi.com	TRUE	/	FALSE	1924905600	__dfp	a024a63691b0794265b1686b3a5de9a0a625f8419f644d63767c2861187cd08163@1506827784123@1504235784123
.iqiyi.com	TRUE	/	FALSE	1819597047	__uuid	86fc7c7e-b6ea-ad5f-afeb-dbc23ae52788
.iqiyi.com	TRUE	/	FALSE	1504322213	c241450289006	1504235813093
.iqiyi.com	TRUE	/	FALSE	1535794849	i18n001	true
.iqiyi.com	TRUE	/	FALSE	1535773046	play_stream	1
.m.iqiyi.com	TRUE	/	FALSE	1535773047	Hm_lvt_5df871ab99f94347b23ca224fc7d013f	1504237047
www.iqiyi.com	FALSE	/	FALSE	1819595783	__uuid	bae6212e-e4d9-2741-cdb0-0406aa54d002
<pre><code>


.iqiyi.com	TRUE	/	FALSE	3651720694	P00001	a5rahekOUu0GPBPhkYassdWu6Nwzv7gxvACLbQlZm1RxghQ3DUOJRZYQut6y9vXNqNc70

.iqiyi.com	TRUE	/	FALSE	1512011808	P00003	1450289006


and then? How to do it

===

**Comment by denobisipsis** [comment]
Found...6 links 
Qual 3840x1848 has 13 parts and 1.65GB
Qual 1920x928 has 13 parts and 611.14MB
Qual 1280x616 has 13 parts and 297.72MB
Qual 1040x504 has 7 parts and 142.14MB
Qual 744x360 has 7 parts and 92.73MB
Qual 448x216 has 7 parts and 35.38MB

As user paste 1450289006
and as password a5rahekOUu0GPBPhkYassdWu6Nwzv7gxvACLbQlZm1RxghQ3DUOJRZYQut6y9vXNqNc70

**Comment by denobisipsis** [comment]
Try it and delete these comments

**Comment by lki2019** [comment]
Thank you,
That my own operation, then how to get the following data?


Found ... 6 links
Qual 3840x1848 has 13 parts and 1.65GB
Qual 1920x928 has 13 parts and 611.14MB
Qual 1280x616 has 13 parts and 297.72MB
Qual 1040x504 has 7 parts and 142.14MB
Qual 744x360 has 7 parts and 92.73MB
Qual 448x216 has 7 parts and 35.38MB

As user paste 1450289006
and as password a5rahekOUu0GPBPhkYassdWu6Nwzv7gxvACLbQlZm1RxghQ3DUOJRZYQut6y9vXNqNc70

**Comment by denobisipsis** [comment]
Paste url and push search, or copy url with mouse and press paste url in the program,  then the search is launched automatically. When finished, press desired quality

**Comment by denobisipsis** [comment]
dont share user and password

**Comment by lki2019** [comment]
Thank you so much
Your technology is really powerful

**Comment by lki2019** [comment]
I ask more,
Is the real download address available on your software?
I copy the real address, to others, others can be added to the download tool to download it?

**Comment by denobisipsis** [comment]
If you mean the mp4 url for every part, i can modify the script yo show it.

**Comment by lki2019** [comment]
I mean this way:

Such as http://www.iqiyi.com/v_19rr8ketuo.html#vfrm=24-9-0-1

I use the member account login to watch, export cookies
And then use your software can be downloaded,

But for example, I have a friend also want to download this, he has no member account,

I can be a complete real download address, sent to him,

He himself added to the download tool to download

**Comment by lki2019** [comment]
I mean this way:

Such as http://www.iqiyi.com/v_19rr8ketuo.html#vfrm=24-9-0-1

I use the member account login to watch, export cookies
And then use your software can be downloaded,

But for example, I have a friend also want to download this, he has no member account,

I can be a complete real download address, sent to him,

He himself added to the download tool to download

**Comment by denobisipsis** [comment]
You can share your user and password, and the links too. Now the program shows you all the final links that can be shared to download them

**Comment by lki2019** [comment]
Download finished,
I opened the download directory to see
144 MB in size,
Just a fragment,
Is not it complete?

**Comment by denobisipsis** [comment]
which quality?

the program downloads all the parts and mux them at the end. If your bandwith is fast there would be no problem.

**Comment by lki2019** [comment]
4K

Download for some time, supposedly should not only so big ah

**Comment by denobisipsis** [comment]
13 parts. Wait to download them all. If some fails repeat the search to download only the missing parts, als they have expiration time.

**Comment by lki2019** [comment]
There was a prompt in the download process:

channel not supported or corrupted module

**Comment by denobisipsis** [comment]
RElaunch program

**Comment by lki2019** [comment]
![qq 20170902224816](https://user-images.githubusercontent.com/30022431/29996449-1872e170-9031-11e7-9b4c-43c714d77beb.png)

**Comment by denobisipsis** [comment]
Try it, it works. If you donate there will be no more messages

**Comment by lki2019** [comment]
![1](https://user-images.githubusercontent.com/30022431/29996484-e325bd16-9031-11e7-8d44-027023403173.png)
I try to download 4K quality again to see if this file is complete

**Comment by lki2019** [comment]
Software suggested that the download is completed, but I downloaded the catalog to find, there is no such documents ah?

![3333](https://user-images.githubusercontent.com/30022431/29996574-c7d68732-9033-11e7-968f-a3a1c6d15d6f.png)


The software function can add a full quality of all the sub-address, derived to the local?

**Comment by denobisipsis** [comment]
Ok, maybe is a problem with the names of the file and folders. Try changing download's folder and give a name in latin chars. For every part you should see the size of the converted mpeg ts, if it shows 1.00B then there was a problem.

**Comment by denobisipsis** [comment]
here you have

![qiyi](https://user-images.githubusercontent.com/5153781/29996694-ab130092-9003-11e7-8a75-72f323746a23.jpg)

**Comment by lki2019** [comment]
Yep,
I copied the program to a pure letter of the path to see if the download is complete, complete no,

In addition, in fact, derived to the local quality options, only export 1080p and 4K quality on the line,

Export format if it is. M3u8 this is the best, because you can use m3u8 downloader download,

**Comment by lki2019** [comment]
I changed the path, the download is successful, the file is complete! The The

Just download the way will roll back several times. Time is a bit long
![99999](https://user-images.githubusercontent.com/30022431/29996917-1e812618-903a-11e7-80f0-8fb4afeb9db0.png)

**Comment by lki2019** [comment]
<pre><code>

Found...6 links 
Qual 3840x1848 has 13 parts and 1.65GB
Item 3840x1848 13/13 18.45MB 60/60 100.00 % http://1.31.174.139/videos/v0/20170804/9c/f3/9bae1de912a7f59074f098701f2857d3.f4v?key=0a42e913db63e35df3797da2b6b0ee35c&dis_k=031084fb7f4596cec552259f1b6c3eef7&dis_t=1504367964&dis_dz=CNC-NeiMeng&dis_st=42&src=iqiyi.com&uuid=3a1240ea-59aad55c-87&qd_vipres=0&qd_stert=2288080&qd_vipdyn=0&qd_p=3a1240ea&qd_tvid=748017100&qd_src=1702633101b340d8917a69cf8a4b8c7c&qd_aid=215462001&qd_index=13&qd_vip=1&qd_ip=3a1240ea&qd_uid=1450289006&qd_k=41faf9f288e51c9b7c0867c274d4f394&qd_tm=1504367932443
Item 3840x1848 12/13 76.29MB 59/60 98.33 % http://1.31.174.142/videos/v0/20170804/9c/f3/b8ec7c2276f9d4332a9f182bfb77e55f.f4v?key=07a2037f1e79b41ce76d6ba7fb5948bbf&dis_k=04605c4d9e3b5a88ffe511902b139f4b2&dis_t=1504367963&dis_dz=CNC-NeiMeng&dis_st=42&src=iqiyi.com&uuid=3a1240ea-59aad55b-86&qd_vipres=0&qd_stert=2094056&qd_vipdyn=0&qd_p=3a1240ea&qd_tvid=748017100&qd_src=1702633101b340d8917a69cf8a4b8c7c&qd_aid=215462001&qd_index=12&qd_vip=1&qd_ip=3a1240ea&qd_uid=1450289006&qd_k=41faf9f288e51c9b7c0867c274d4f394&qd_tm=1504367932443
Item 3840x1848 11/13 139.64MB 58/60 96.67 % http://1.31.174.138/videos/v0/20170804/9c/f3/2a5f48a7cab517b5472cdc4414b7da17.f4v?key=05ce8d49b9549d02d76d6ba7fb5948bbf&dis_k=029bad0ae653b09b35c7fcc2c0ca730d9&dis_t=1504367963&dis_dz=CNC-NeiMeng&dis_st=42&src=iqiyi.com&uuid=3a1240ea-59aad55b-76&qd_vipres=0&qd_stert=1902867&qd_vipdyn=0&qd_p=3a1240ea&qd_tvid=748017100&qd_src=1702633101b340d8917a69cf8a4b8c7c&qd_aid=215462001&qd_index=11&qd_vip=1&qd_ip=3a1240ea&qd_uid=1450289006&qd_k=41faf9f288e51c9b7c0867c274d4f394&qd_tm=1504367932443
Item 3840x1848 10/13 148.64MB 57/60 95.00 % http://1.31.174.132/videos/v0/20170804/9c/f3/ed7d5532c47ad81189dacb362cd6c1a4.f4v?key=08ad3fe04133b84b9cea1009bbd3e6193&dis_k=0d4a3c3f86deb84877063fd4fb175dbcd&dis_t=1504367962&dis_dz=CNC-NeiMeng&dis_st=42&src=iqiyi.com&uuid=3a1240ea-59aad55a-77&qd_vipres=0&qd_stert=1713523&qd_vipdyn=0&qd_p=3a1240ea&qd_tvid=748017100&qd_src=1702633101b340d8917a69cf8a4b8c7c&qd_aid=215462001&qd_index=10&qd_vip=1&qd_ip=3a1240ea&qd_uid=1450289006&qd_k=41faf9f288e51c9b7c0867c274d4f394&qd_tm=1504367932443
Item 3840x1848 9/13 150.10MB 56/60 93.33 % http://1.31.174.140/videos/v0/20170804/9c/f3/6d7a04289d400b0f3138dd82b5c6d873.f4v?key=0b5604860ec345af5cea1009bbd3e6193&dis_k=027d1ce2d210fc7d98004c03d18274a4d&dis_t=1504367962&dis_dz=CNC-NeiMeng&dis_st=42&src=iqiyi.com&uuid=3a1240ea-59aad55a-78&qd_vipres=0&qd_stert=1522004&qd_vipdyn=0&qd_p=3a1240ea&qd_tvid=748017100&qd_src=1702633101b340d8917a69cf8a4b8c7c&qd_aid=215462001&qd_index=9&qd_vip=1&qd_ip=3a1240ea&qd_uid=1450289006&qd_k=41faf9f288e51c9b7c0867c274d4f394&qd_tm=1504367932443
Item 3840x1848 8/13 109.66MB 55/60 91.67 % http://1.31.174.134/videos/v0/20170804/9c/f3/383fa861ef00517e443215c87cfedf4c.f4v?key=05babbfd987f380ce2a00cf04e8a146a0&dis_k=0a3a68249432f22bd877c34fc67494be2&dis_t=1504367961&dis_dz=CNC-NeiMeng&dis_st=42&src=iqiyi.com&uuid=3a1240ea-59aad559-79&qd_vipres=0&qd_stert=1330573&qd_vipdyn=0&qd_p=3a1240ea&qd_tvid=748017100&qd_src=1702633101b340d8917a69cf8a4b8c7c&qd_aid=215462001&qd_index=8&qd_vip=1&qd_ip=3a1240ea&qd_uid=1450289006&qd_k=41faf9f288e51c9b7c0867c274d4f394&qd_tm=1504367932443
Item 3840x1848 7/13 167.60MB 54/60 90.00 % http://wscctcdn.inter.qiyi.com/videos/v0/20170804/9c/f3/e40d88bf78392838278833ea2e3bd725.f4v?key=007abce884f27d4cc2a00cf04e8a146a0&dis_k=4f1256b81aaca7aac3347332a7d2a1f0&dis_t=1504367961&src=iqiyi.com&uuid=1b48422-59aad559-7a&qd_vipres=0&qd_stert=1140578&qd_vipdyn=0&qd_p=3a1240ea&qd_tvid=748017100&qd_src=1702633101b340d8917a69cf8a4b8c7c&qd_aid=215462001&qd_index=7&qd_vip=1&qd_ip=3a1240ea&qd_uid=1450289006&qd_k=41faf9f288e51c9b7c0867c274d4f394&qd_tm=1504367932443
Item 3840x1848 6/13 144.60MB 53/60 88.33 % http://wscctcdn.inter.qiyi.com/videos/v0/20170804/9c/f3/5c03884341ba5d94239b2bcabba8a4cd.f4v?key=060035d5750ca529a2a00cf04e8a146a0&dis_k=8002439fd9ea212411b5316985612e25&dis_t=1504367961&src=iqiyi.com&uuid=1b48422-59aad559-89&qd_vipres=0&qd_stert=952338&qd_vipdyn=0&qd_p=3a1240ea&qd_tvid=748017100&qd_src=1702633101b340d8917a69cf8a4b8c7c&qd_aid=215462001&qd_index=6&qd_vip=1&qd_ip=3a1240ea&qd_uid=1450289006&qd_k=41faf9f288e51c9b7c0867c274d4f394&qd_tm=1504367932443
Item 3840x1848 5/13 142.73MB 52/60 86.67 % http://1.31.174.142/videos/v0/20170804/9c/f3/3c45f3864f5748391e790b1d8102f39f.f4v?key=0de1388df8546bb6e7df137410445f943&dis_k=03bb72d592e242e2151f5a7f9742e290a&dis_t=1504367960&dis_dz=CNC-NeiMeng&dis_st=42&src=iqiyi.com&uuid=3a1240ea-59aad558-88&qd_vipres=0&qd_stert=767233&qd_vipdyn=0&qd_p=3a1240ea&qd_tvid=748017100&qd_src=1702633101b340d8917a69cf8a4b8c7c&qd_aid=215462001&qd_index=5&qd_vip=1&qd_ip=3a1240ea&qd_uid=1450289006&qd_k=41faf9f288e51c9b7c0867c274d4f394&qd_tm=1504367932443
Item 3840x1848 4/13 155.42MB 51/60 85.00 % http://1.31.174.134/videos/v0/20170804/9c/f3/2d8dda2ec4272bc00528127d9ab303bf.f4v?key=0e547b041d75c90167df137410445f943&dis_k=0c6c44b5e70def3eaf7259147675d2fea&dis_t=1504367960&dis_dz=CNC-NeiMeng&dis_st=42&src=iqiyi.com&uuid=3a1240ea-59aad558-86&qd_vipres=0&qd_stert=575768&qd_vipdyn=0&qd_p=3a1240ea&qd_tvid=748017100&qd_src=1702633101b340d8917a69cf8a4b8c7c&qd_aid=215462001&qd_index=4&qd_vip=1&qd_ip=3a1240ea&qd_uid=1450289006&qd_k=41faf9f288e51c9b7c0867c274d4f394&qd_tm=1504367932443
Item 3840x1848 3/13 151.11MB 50/60 83.33 % http://netcncallcnc.inter.iqiyi.com/videos/v0/20170804/9c/f3/c32768dbb70c611775b976e479042f86.f4v?key=02e055889ae2f1e3454dc7592fa6ecb1b&dis_k=1fd06027a9a5898004dddb85b6078350&dis_t=1504367959&src=iqiyi.com&uuid=3a1240ea-59aad557-76&qd_vipres=0&qd_stert=381385&qd_vipdyn=0&qd_p=3a1240ea&qd_tvid=748017100&qd_src=1702633101b340d8917a69cf8a4b8c7c&qd_aid=215462001&qd_index=3&qd_vip=1&qd_ip=3a1240ea&qd_uid=1450289006&qd_k=41faf9f288e51c9b7c0867c274d4f394&qd_tm=1504367932443
Item 3840x1848 2/13 120.71MB 49/60 81.67 % http://netcncallcnc.inter.iqiyi.com/videos/v0/20170804/9c/f3/706ad4c74c97207e8f744b7bd84739c2.f4v?key=0c33c54661cd2df6154dc7592fa6ecb1b&dis_k=3117da0d5502f3dc45acb0aa0406b703&dis_t=1504367959&src=iqiyi.com&uuid=3a1240ea-59aad557-77&qd_vipres=0&qd_stert=195466&qd_vipdyn=0&qd_p=3a1240ea&qd_tvid=748017100&qd_src=1702633101b340d8917a69cf8a4b8c7c&qd_aid=215462001&qd_index=2&qd_vip=1&qd_ip=3a1240ea&qd_uid=1450289006&qd_k=41faf9f288e51c9b7c0867c274d4f394&qd_tm=1504367932443
Item 3840x1848 1/13 166.28MB 48/60 80.00 % http://1.31.174.138/videos/v0/20170804/9c/f3/a6f87ed3b7f03ef65b57b392f531e2f5.f4v?key=009bed9ed917a8add2a76344f6d19142&dis_k=0aca27769e7a286231bad3d60693affc8&dis_t=1504367958&dis_dz=CNC-NeiMeng&dis_st=42&src=iqiyi.com&uuid=3a1240ea-59aad556-78&qd_vipres=0&qd_stert=0&qd_vipdyn=0&qd_p=3a1240ea&qd_tvid=748017100&qd_src=1702633101b340d8917a69cf8a4b8c7c&qd_aid=215462001&qd_index=1&qd_vip=1&qd_ip=3a1240ea&qd_uid=1450289006&qd_k=41faf9f288e51c9b7c0867c274d4f394&qd_tm=1504367932443
<pre><code>
![qq 20170903001935](https://user-images.githubusercontent.com/30022431/29997123-d47ef7bc-903d-11e7-8671-8a142661ef4b.png)



  libpostproc    54.  0.100 / 54.  0.100
[http @ 04217900] HTTP error 405 Not Allowed
http://1.31.174.140/videos/v0/20170804/9c/f3/6d7a04289d400b0f3138dd82b5c6d873.f4
v?key=0b5604860ec345af5cea1009bbd3e6193&dis_k=027d1ce2d210fc7d98004c03d18274a4d&
dis_t=1504367962&dis_dz=CNC-NeiMeng&dis_st=42&src=iqiyi.com&uuid=3a1240ea-59aad5
5a-78&qd_vipres=0&qd_stert=1522004&qd_vipdyn=0&qd_p=3a1240ea&qd_tvid=748017100&q
d_src=1702633101b340d8917a69cf8a4b8c7c&qd_aid=215462001&qd_index=9&qd_vip=1&qd_i
p=3a1240ea&qd_uid=1450289006&qd_k=41faf9f288e51c9b7c0867c274d4f394&qd_tm=1504367
932443: Server returned 4XX Client Error, but not one of 40{0,1,3,4}
ffmpeg version 3.1.5 Copyright (c) 2000-2016 the FFmpeg developers



m3u8 downloader suggested error

Pour out the address, can not download the tool to download it?

**Comment by lki2019** [comment]
I first close the issues, so that people see less,
Boss, direct reply like

**Comment by lki2019** [comment]
Can you add one of these features?

http://www.xXXX.com/php?url=http://www.iqiyi.com/v_19rr8ketuo.html#vfrm=24-9-0-1

After submitting the visit, get an API interface data, which has the highest quality of all the segment information

So easy to copy the real download address, download the tool to download
