### ISSUE TITLE
How much is this salt?

### ISSUE THREAD

**Issue by meteorlad** [denobisipsis/adownloader#96]
If the address is as follows:

```
http://cache.m.iqiyi.com/jp/tmts/778264800/d04b3625c1bca711ce6126594dbfda76/?uid=1210611545&cupid=qc_100001_100186&platForm=h5&qyid=80tpw6x1plep3ssytvsvmcu5&agenttype=13&type=mp4&nolimit=&k_ft1=8&rate=1&sgti=13_80tpw6x1plep3ssytvsvmcu5_1504532374406&codeflag=1&qdv=1&qdx=n&qdy=x&qds=0&__jsT=sijsc&t=1504532376024&src=02020031010000000000&vf=81780f7d141090ba01a0f99629a76dd1&callback=tmtsCallback
```
How much is the salt ?

**Comment by denobisipsis** [comment]
md5("/vms?key=fvip&src=1702633101b340d8917a69cf8a4b8c7c&tvId=768758500&vid=4365495db4bbe628f886ecffd0fc4b0c&vinfo=1&tm=3679&qyid=04bbf817addf54fe17a65c01c9e8bde5&puid=1210611545&authKey=40e9dfaddacc9b71e58a5a4b8bcbf198&um=1&pf=b6c13e26323c537d&thdk=&thdt=&rs=1&k_tag=1&qdx=n&qdv=3&ppt=0"."**t6hrq6k0n6n6k6qdh6tje6wpb62v7654**");

&vf=c36e686bee5fdd01bf667c023d482552

md5("/jp/tmts/778264800/d04b3625c1bca711ce6126594dbfda76/?uid=1210611545&cupid=qc_100001_100186&platForm=h5&qyid=80tpw6x1plep3ssytvsvmcu5&agenttype=13&type=mp4&nolimit=&k_ft1=8&rate=1&sgti=13_80tpw6x1plep3ssytvsvmcu5_1504532374406&codeflag=1&qdv=1&qdx=n&qdy=x&qds=0&__jsT=sijsc&t=1504532376024&src=02020031010000000000&callback=tmtsCallback"."**3sj8xof48xof4tk9f4tk9ypgk9ypg5ul**");


&vf=81780f7d141090ba01a0f99629a76dd1

**Comment by meteorlad** [comment]
Thanks

**Comment by meteorlad** [comment]
qyid=80tpw6x1plep3ssytvsvmcu5 and t=1504532376024 and sgti=13_80tpw6x1plep3ssytvsvmcu5_1504532374406
How do we calculate that？

**Comment by denobisipsis** [comment]
you should post all the cache string as

"/jp/tmts/778264800/d04b3625c1bca711ce6126594dbfda76/?uid=1210611545&cupid=qc_100001_100186&platForm=h5&qyid=80tpw6x1plep3ssytvsvmcu5&agenttype=13&type=mp4&nolimit=&k_ft1=8&rate=1&sgti=13_80tpw6x1plep3ssytvsvmcu5_1504532374406&codeflag=1&qdv=1&qdx=n&qdy=x&qds=0&__jsT=sijsc&t=1504532376024&src=02020031010000000000&callback=tmtsCallback"

the key to use one or another salt ist the src

**Comment by meteorlad** [comment]
```
http://cache.m.iqiyi.com/jp/tmts/778264800/d04b3625c1bca711ce6126594dbfda76/?uid=1210611545&cupid=qc_100001_100186&platForm=h5&qyid=80tpw6x1plep3ssytvsvmcu5&agenttype=13&type=mp4&nolimit=&k_ft1=8&rate=1&sgti=**13_80tpw6x1plep3ssytvsvmcu5_1504532374406**&codeflag=1&qdv=1&qdx=n&qdy=x&qds=0&__jsT=sijsc&t=**1504532376024**&src=02020031010000000000&vf=81780f7d141090ba01a0f99629a76dd1&callback=tmtsCallback
```
How do I get the two values that are bold?

**Comment by denobisipsis** [comment]
you dont need these values. Use this address

http://cache.video.qiyi.com/vms?key=fvip&src=1702633101b340d8917a69cf8a4b8c7c&tvId=778264800&vid=d04b3625c1bca711ce6126594dbfda76&vinfo=1&tm=506&qyid=&puid=&authKey=19115ecc0da9cdb0310534b641f72d63&um=1&pf=b6c13e26323c537d&thdk=&thdt=&rs=1&k_tag=1&qdv=3&vf=cad61b972a7198782f896e2cedad81d4



$authkey=md5(md5("")."506"."778264800");

$cache= "/vms?key=fvip&src=1702633101b340d8917a69cf8a4b8c7c&tvId=778264800&vid=d04b3625c1bca711ce6126594dbfda76&vinfo=1&tm=506&qyid=&puid=&authKey=$authkey&um=1&pf=b6c13e26323c537d&thdk=&thdt=&rs=1&k_tag=1&qdv=3";

$vf=md5($cache."u6fnp3eok0dpftcq9qbr4n9svk8tqh7u");

echo gzinflate(substr(curl_proxy("http://cache.video.qiyi.com$cache&vf=$vf"),10));

**Comment by meteorlad** [comment]
This address only gets the address in the FLV format, if you want to get the mp4 format or the m3u8 format?

**Comment by denobisipsis** [comment]
No, you get mp4 files. With the f4v links you should make another call adding http://data.video.qiyi.com/videos

**Comment by meteorlad** [comment]
Can say the specific call way.

**Comment by denobisipsis** [comment]
Call the cache and get all the f4v links. Then you should make another call adding http://data.video.qiyi.com/videos to each link.

For example

http://data.video.qiyi.com/videos/v0/20170904/ac/ad/d6e182579032e31be0caf8d9294c4b26.f4v?qd_tvid=778264800&qd_vipres=2&qd_index=1&qd_aid=215462001&qd_stert=0&qd_scc=cfd313daf2d57c7afdb7c35649a50b81&qd_sc=2dc4e35ec7f1d269bcedef6f44537c62&qd_p=3b29eda7&qd_ip=3b29eda7&qd_k=cad61b972a7198782f896e2cedad81d4&qd_src=1702633101b340d8917a69cf8a4b8c7c&qd_vipdyn=2&qd_uid=0&qd_tm=1504788097608&qd_vip=1

but this only works if the video isnt vip. For vip is more complex.
